#!/bin/sh

# this doesn't actually prevent stuff from just turning the camera on >_>
# feels bad.

# Touchpad xinput id
TP=$(xinput list | grep "Integrated Camera" | cut -f2 | cut -f2 -d=)

## remember to change the above option so that it corresponds to the correct xinput id
# run: xinput list
# if xinput isn't installed, install it you dummy!

if xinput list-props $TP | grep -E "Device Enabled \([0-9]{3}\):[[:space:]]*1" > /dev/null
then
    xinput disable $TP
    notify-send -u low -i camera "Webcam" "Disabled"
else
    xinput enable $TP
    notify-send -u low -i camera "Webcam" "Enabled"
fi
